# Generated by Django 2.2.5 on 2019-09-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('order', models.IntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Paper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.TextField()),
                ('papers', models.ManyToManyField(through='question.PaperQuestion', to='question.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Question'),
        ),
    ]
